### ISSUE TITLE
Pull yapf sources from git instead of tar

### ISSUE THREAD

**Issue by TheGhostHuCodes** [conda-forge/yapf-feedstock#17]
I was looking into doing #16, but couldn't figure out the expected location of the `source:` tar url location. It looks like the yapf repo doesn't contain an `archive/` subdirectory with tars of sources anymore.

Would it be ok to switch the `source:` section over to pulling from git instead of using a tar?

**Comment by TheGhostHuCodes** [comment]
Whoops, @starcruiseromega pointed me in the right direction. Looks like the tars can be found here:

https://github.com/google/yapf/releases

So do we want to stick with tars or move over to using git tags instead?

**Comment by vamega** [comment]
I don't see one as better than the other.
I was using tar files since it seemed like what all the other recipies were using.

Is there any advantage of switching to a git tag?

**Comment by TheGhostHuCodes** [comment]
I guess I could go either way on this as well. The two advantages I can see are:

1. As a newcomer to `conda-forge`, the feedstock stuff, and github releases, I had a hard time figuring out where the tars lived (as seen in my comment above).
1. After figuring out where to download the tar, I also had to go and calculate the SHA256 hash. If we used the git tag I could have just gone over to the `yapf` repo and copied the git tag hash directly from there.

**Comment by jakirkham** [comment]
In conda-forge we prefer using tarballs to git clones. Unless there is some special reason not to, this is generally the rule. Please see this [relevant doc section]( https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos ).

**Comment by TheGhostHuCodes** [comment]
Ah, good to know. Thanks for setting me straight!
